- hosts: localhost
  become: no
  connection: local
  gather_facts: no
  vars:
    image_bucket: img.prod.s3.kerokero.rororo.xyz
  roles:
    # - { tags: sg, role: aws/security-group } not support IPv6
    - { tags: s3, role: aws/s3 }
    - { tags: iamrole, role: aws/iamrole }
    - { tags: r53, role: aws/route53 }
