- name: Clone scripts repo
  git:
    repo: https://github.com/rmanzoku/scripts.git
    dest: "/usr/local/github.com/rmanzoku/scripts"
    version: master

- name: Create profile file
  copy:
    content: |
      export PATH=/usr/local/github.com/rmanzoku/scripts:$PATH
    dest: /etc/profile.d/99_rmanzoku.sh

- cron:
    user: root
    env: yes
    name: PATH
    value: /usr/local/github.com/rmanzoku/scripts:/usr/local/bin:/usr/bin:/bin

- cron:
    user: root
    env: yes
    name: WEBHOOK_URL
    value: "{{ slack_webhook }}"

- cron:
    user: root
    env: yes
    name: CHANNEL
    value: "#audit"

- cron:
    user: root
    name: audit s3 img.prod.s3.kerokero.rororo.xyz
    minute: "10"
    hour: "3"
    job: "aws s3 ls s3://img.prod.s3.kerokero.rororo.xyz --recursive --human-readable --summarize | tail -n 2 | post2slack -m 'S3 summerize img.prod.s3.kerokero.rororo.xyz'"
