- git:
    repo: https://github.com/rmanzoku/mastodon.git
    version: live
    dest: /home/mastodon/live
    depth: 1
  become: yes
  become_user: mastodon

- shell: /home/mastodon/.rbenv/bin/rbenv install
  args:
    chdir: /home/mastodon/live
  become: yes
  become_user: mastodon
  when: RUBY_UPDATE is defined and RUBY_UPDATE is True

- name: "gem install bundler"
  gem:
    executable: /home/mastodon/.rbenv/shims/gem
    name: bundler
    user_install: no
  become: yes
  become_user: mastodon

- name: "Create bundle directory"
  file: state=directory path=/home/mastodon/lib/github.com/rmanzoku/mastodon/bundle owner=mastodon group=mastodon

- name: "bundle install"
  bundler:
    executable: /home/mastodon/.rbenv/shims/bundle
    chdir: /home/mastodon/live/
    deployment_mode: yes
    exclude_groups:
      - development
      - test
    gem_path: /home/mastodon/lib/github.com/rmanzoku/mastodon/bundle
  become: yes
  become_user: mastodon

- name: yarn install
  shell: yarn install
  args:
    chdir: /home/mastodon/live
  become: yes
  become_user: mastodon

- name: Copy env file
  copy: src=home/mastodon/live/.env.production dest=/home/mastodon/live/.env.production

- name: bundle exec rails db:migrate
  shell: /home/mastodon/.rbenv/shims/bundle exec rails db:migrate
  args:
    chdir: /home/mastodon/live
  environment:
    RAILS_ENV: production
  become: yes
  become_user: mastodon

- name: bundle exec rails assets:precompile
  shell: /home/mastodon/.rbenv/shims/bundle exec rails assets:precompile
  args:
    chdir: /home/mastodon/live
  environment:
    RAILS_ENV: production
  become: yes
  become_user: mastodon
