- set_fact:
    mastodon_version: 1.1.2
    ruby_version: 2.4.1

# - unarchive:
#     src: https://github.com/tootsuite/mastodon/archive/v{{ mastodon_version }}.tar.gz
#     dest: /home/mastodon/src/
#     owner: mastodon
#     group: mastodon
#     copy: no

- file: state=link src=/home/mastodon/src/mastodon-{{ mastodon_version }} dest=/home/mastodon/live

# - shell: /home/mastodon/.rbenv/bin/rbenv install
#   args:
#     chdir: /home/mastodon/live
#   become: yes
#   become_user: mastodon

# - gem:
#     executable: /home/mastodon/.rbenv/shims/gem
#     name: bundler
#     user_install: no
#   become: yes
#   become_user: mastodon

# - name: "bundle install"
#   bundler:
#     executable: /home/mastodon/.rbenv/shims/bundle
#     chdir: "/home/mastodon/live/"
#     deployment_mode: yes
#     exclude_groups:
#       - development
#       - test
#   become: yes
#   become_user: mastodon

# - shell: yarn install
#   args:
#     chdir: /home/mastodon/live
#   become: yes
#   become_user: mastodon

- copy: src=home/mastodon/live/.env.production dest=/home/mastodon/live/.env.production

# - shell: /home/mastodon/.rbenv/shims/bundle exec rails db:setup
#   args:
#     chdir: /home/mastodon/live
#   environment:
#     RAILS_ENV: production
#   become: yes
#   become_user: mastodon

# - shell: /home/mastodon/.rbenv/shims/bundle exec rails assets:precompile
#   args:
#     chdir: /home/mastodon/live
#   environment:
#     RAILS_ENV: production
#   become: yes
#   become_user: mastodon
