- name: "Update apt cache"
  apt: update_cache=yes
  changed_when: no

- apt: name={{ item }} state=present force=yes
  with_items:
    - git
    - ntp
    - gcc
    - make
    - unzip
    - linux-aws

- name: Update security
  apt: name={{ item }} state=latest force=yes
  with_items:
    - openssl
    - libssl1.0.0
    - libssl-dev
    - libssl-doc

- name: lltsv
  get_url:
    url: "https://github.com/sonots/lltsv/releases/download/v0.3.0/lltsv_linux_amd64"
    dest: /usr/local/bin/lltsv
    mode: 0755

- apt: name={{ item }} state=present
  with_items:
    - jq
    - python3-pip

- pip: name=awscli
