- file: path=/etc/nginx state=directory owner=root group=root mode=0755

- synchronize: src=etc/nginx/ dest=/etc/nginx/ recursive=yes delete=yes owner=no group=no perms=no rsync_opts="--exclude=common"

- name: nginx config test
  shell: sudo /usr/local/nginx/sbin/nginx -t -c /etc/nginx/nginx.conf warn=no

- systemd: name=nginx.service state=started

- systemd: name=nginx.service state=reloaded
