# https://mackerel.io/file/script/setup-all-apt-v2.sh
- name: Add apt key
  apt_key:
    url: "https://mackerel.io/file/cert/GPG-KEY-mackerel-v2"

- name: Add apt repo
  apt_repository:
    repo: "deb http://apt.mackerel.io/v2/ mackerel contrib"

- name: Update apt
  apt: update_cache=yes
  changed_when: no

- name: Install mackerel-agent and plugins
  apt: name={{ item }} state=present
  with_items:
    - mackerel-agent
    - mackerel-agent-plugins
    - mackerel-check-plugins

- name: Make conf.d directory
  file: state=directory path=/etc/mackerel-agent/conf.d owner=root group=root

- name: Copy conf from template
  template:
    src: etc/mackerel-agent/mackerel-agent.conf.j2
    dest: /etc/mackerel-agent/mackerel-agent.conf
    owner: root
    group: root
    mode: 0644

- name: mackerel-agent started
  systemd: name=mackerel-agent.service state=started

- name: mackerel-agent reloaded
  systemd: name=mackerel-agent.service state=reloaded
